<a href="https://colab.research.google.com/github/Davichobacter/ds-4geeks/blob/main/Gravitational_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The gravity model relate the amount of commerce with the size of countries, its
distance an its international trade.

Using the datasets:
- Locations
- Importations
- Exportations
- Gross domestic products
- Country names

The following work need to establish empirical evidence in Colombia, could
test any model to support or not the hypothesis, for instance:
$$ y_{ij} = β_0 + β_1 gpd_j + β_2 dist_{ij} $$
Where the $ y_{ij} $ is the amount of international trade (importations+exportations)
between the $ i $ country with the $ j $ country, $ gdp_j $ is the domestic product $ j $ and
$ dist_{ij} $ could be a measure of distance among the countries $ i $ and $ j $.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url_locations = ('https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/Countries-location(google).csv')
url_importations = ('https://raw.githubusercontent.com/it-ces/Datasets/main/dane-importaciones.csv')
url_exportations = ('https://raw.githubusercontent.com/it-ces/Datasets/main/dane-exportaciones.csv')
url_gdp = ('https://raw.githubusercontent.com/it-ces/Datasets/main/wbdata-gdp-lifeExp-time-series.csv')
url_names = ('https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/world.csv')

In [3]:
df_locations = pd.read_csv(url_locations)
df_importations = pd.read_csv(url_importations)
df_exportations = pd.read_csv(url_exportations)
df_gdp = pd.read_csv(url_gdp)
df_names = pd.read_csv(url_names)

In [4]:
df_locations.head()

  country    latitude    longitude                  name
0      AD  42.546.245    1.601.554               Andorra
1      AE  23.424.076   53.847.818  United Arab Emirates
2      AF   3.393.911   67.709.953           Afghanistan
3      AG  17.060.816  -61.796.428   Antigua and Barbuda
4      AI  18.220.554  -63.068.615              Anguilla

In [5]:
df_importations.head()

,Código,País,Enero - Diciembre 1980,Unnamed: 3,Enero - Diciembre 1981,Unnamed: 5,Enero - Diciembre 1982,Unnamed: 7,Enero - Diciembre 1983,Unnamed: 9,...,Unnamed: 153,Unnamed: 154,Enero - diciembre 2023,Unnamed: 156,Unnamed: 157,Unnamed: 158,Enero - mayo 2024,Unnamed: 160,Unnamed: 161,Unnamed: 162
0,NaN,NaN,Dólares CIF,NaN,Dólares CIF,NaN,Dólares CIF,NaN,Dólares CIF,NaN,...,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Total,"4,662,604,264",NaN,"5,199,155,629",NaN,"5,477,701,184",NaN,"4,968,079,999",NaN,...,"71,446,374,137","40,161,000,492","62,796,636,363","273,157,297,690,829","59,445,304,522","38,053,556,648","25,911,804,734","100,871,611,816,413","24,572,515,154","17,292,003,534"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13.0,Afganistán,"135,485",NaN,0,NaN,"74,442",NaN,"49,238",NaN,...,"449,430","949,692","27,752","116,961,928","27,388",565,0,0,0,0

In [6]:
df_importations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 394 entries, 0 to 393
Columns: 163 entries, Código to Unnamed: 162
dtypes: float64(42), object(121)
memory usage: 501.9+ KB

In [7]:
df_imp_paises = pd.DataFrame(df_importations['País'].unique())

In [8]:
df_exportations.head()

,Código,País,1970,Unnamed: 3,Unnamed: 4,Unnamed: 5,1971,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,2022,Unnamed: 211,Unnamed: 212,Unnamed: 213,2023,Unnamed: 215,Unnamed: 216,2024*,Unnamed: 218,Unnamed: 219
0,NaN,NaN,Kilos Netos,Dólares FOB,Pesos FOB,NaN,Kilos Netos,Dólares FOB,Pesos FOB,NaN,...,Kilos Netos,Dólares FOB,Pesos FOB,NaN,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB
1,NaN,Total,"7,156,313,083","735,657,066",-,NaN,"6,293,567,780","690,008,689",-,NaN,...,"102,131,628,696","56,910,136,648","241,607,564,595,030",NaN,"103,191,548,967","49,769,126,318","215,159,245,675,576","45,438,335,252","20,154,157,442","78,522,240,780,348"
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,ZFP Dorado,0,0,0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-
4,13.0,Afganistán,"7,913","4,185",0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-

In [9]:
df_exportations.iloc[:, 5:6].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 5  0 non-null      float64
dtypes: float64(1)
memory usage: 3.2 KB

In [10]:
df_gdp.head()

         value  year incomeLevel region  lifeExp  Gdp
0        Aruba  1960         HIC    LCN   64.152  NaN
1  Afghanistan  1960         LIC    SAS   32.535  NaN
2       Angola  1960         LMC    SSF   38.211  NaN
3      Albania  1960         UMC    ECS   54.439  NaN
4      Andorra  1960         HIC    ECS      NaN  NaN

In [11]:
df_gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13454 entries, 0 to 13453
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   value        13454 non-null  object
 1   year         13454 non-null  int64
 2   incomeLevel  13454 non-null  object
 3   region       13454 non-null  object
 4   lifeExp      12890 non-null  float64
 5   Gdp          5912 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 630.8+ KB

In [12]:
df_names.head()

,id,alpha2,alpha3,ar,bg,cs,da,de,el,en,...,ro,ru,sk,sl,sr,sv,th,uk,zh,zh-tw
0,4,af,afg,أفغانستان,Афганистан,Afghánistán,Afghanistan,Afghanistan,Αφγανιστάν,Afghanistan,...,Afganistan,Афганистан,Afganistan,Afganistan,Avganistan,Afghanistan,อัฟกานิสถาน,Афганістан,阿富汗,阿富汗
1,248,ax,ala,جزر أولاند,Оландски острови,Alandy,Ålandsøerne,Åland,Ώλαντ,Åland Islands,...,Insulele Åland,Аландские острова,Alandy,Ålandski otoki,Olandska Ostrva,Åland,หมู่เกาะโอลันด์,Аландські острови,奥兰,奧蘭
2,8,al,alb,ألبانيا,Албания,Albánie,Albanien,Albanien,Αλβανία,Albania,...,Albania,Албания,Albánsko,Albanija,Albanija,Albanien,แอลเบเนีย,Албанія,阿尔巴尼亚,阿爾巴尼亞
3,12,dz,dza,الجزائر,Алжир,Alžírsko,Algeriet,Algerien,Αλγερία,Algeria,...,Algeria,Алжир,Alžírsko,Alžirija,Alžir,Algeriet,แอลจีเรีย,Алжир,阿尔及利亚,阿爾及利亞
4,16,as,asm,ساموا الأمريكية,Американска Самоа,Americká Samoa,Amerikansk Samoa,Amerikanisch-Samoa,Αμερικανική Σαμόα,American Samoa,...,Samoa americană,Американское Самоа,Americká Samoa,Ameriška Samoa,Američka Samoa,Amerikanska Samoa,อเมริกันซามัว,Американське Самоа,美属萨摩亚,美屬薩摩亞

In [13]:
df_names_paises = pd.DataFrame(df_names['es'].unique())

In [14]:
df_gdp[(df_gdp['value'] == 'Colombia') & (df_gdp['Gdp'].notna())]

          value  year incomeLevel region  lifeExp           Gdp
6551   Colombia  1990         UMC    LCN   68.644   8434.959336
6768   Colombia  1991         UMC    LCN   68.813   8430.222989
6985   Colombia  1992         UMC    LCN   69.038   8598.992021
7202   Colombia  1993         UMC    LCN   69.342   8885.186845
7419   Colombia  1994         UMC    LCN   69.613   9220.501993
7636   Colombia  1995         UMC    LCN   69.933   9518.260141
7853   Colombia  1996         UMC    LCN   70.189   9538.272551
8070   Colombia  1997         UMC    LCN   70.492   9691.028324
8287   Colombia  1998         UMC    LCN   70.738   9578.656012
8504   Colombia  1999         UMC    LCN   70.926   9023.621233
8721   Colombia  2000         UMC    LCN   71.320   9138.318915
8938   Colombia  2001         UMC    LCN   71.502   9146.404852
9155   Colombia  2002         UMC    LCN   71.939   9232.627395
9372   Colombia  2003         UMC    LCN   72.361   9453.328556
9589   Colombia  2004         UMC    LCN   72.695   9816.277588
9806   Colombia  2005         UMC    LCN   73.081  10150.707922
10023  Colombia  2006         UMC    LCN   73.468  10692.727653
10240  Colombia  2007         UMC    LCN   73.837  11272.577980
10457  Colombia  2008         UMC    LCN   74.295  11507.525825
10674  Colombia  2009         UMC    LCN   74.742  11507.717113
10891  Colombia  2010         UMC    LCN   75.033  11890.203077
11108  Colombia  2011         UMC    LCN   75.320  12578.015627
11325  Colombia  2012         UMC    LCN   75.597  12934.965752
11542  Colombia  2013         UMC    LCN   75.827  13465.075044
11759  Colombia  2014         UMC    LCN   76.043  13938.231517
11976  Colombia  2015         UMC    LCN   76.257  14215.688252
12193  Colombia  2016         UMC    LCN   76.471  14358.168218
12410  Colombia  2017         UMC    LCN   76.646  14334.914608
12627  Colombia  2018         UMC    LCN   76.748  14426.434382
12844  Colombia  2019         UMC    LCN   76.752  14616.135124
13061  Colombia  2020         UMC    LCN   74.769  13358.298083
13278  Colombia  2021         UMC    LCN   72.830  14661.213244

In [15]:
df_imp_paises.columns = ['País']
df_imp_paises

                                                  País
0                                                  NaN
1                                                Total
2                                           Afganistán
3                                         Aland, Islas
4                                              Albania
..                                                 ...
387                                            ZFP GEA
388  ZFPE Compañía  Operadora Clinica Hispanoamericana
389                                  ZFP SurColombiana
390      ZFPE Sociedad Portuaria Regional de Cartagena
391  Países no precisados en otra parte y desconocidos

[392 rows x 1 columns]

In [16]:
df_names_paises.columns = ['País']
df_names_paises

                                     País
0                              Afganistán
1                                   Åland
2                                 Albania
3                                 Argelia
4                         Samoa Americana
..                                    ...
243                       Wallis y Futuna
244  República Árabe Saharaui Democrática
245                                 Yemen
246                                Zambia
247                              Zimbabue

[248 rows x 1 columns]

# Limpieza de los Data Sets

## DF Importations

In [17]:
df_importations

,Código,País,Enero - Diciembre 1980,Unnamed: 3,Enero - Diciembre 1981,Unnamed: 5,Enero - Diciembre 1982,Unnamed: 7,Enero - Diciembre 1983,Unnamed: 9,...,Unnamed: 153,Unnamed: 154,Enero - diciembre 2023,Unnamed: 156,Unnamed: 157,Unnamed: 158,Enero - mayo 2024,Unnamed: 160,Unnamed: 161,Unnamed: 162
0,NaN,NaN,Dólares CIF,NaN,Dólares CIF,NaN,Dólares CIF,NaN,Dólares CIF,NaN,...,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Total,"4,662,604,264",NaN,"5,199,155,629",NaN,"5,477,701,184",NaN,"4,968,079,999",NaN,...,"71,446,374,137","40,161,000,492","62,796,636,363","273,157,297,690,829","59,445,304,522","38,053,556,648","25,911,804,734","100,871,611,816,413","24,572,515,154","17,292,003,534"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13.0,Afganistán,"135,485",NaN,0,NaN,"74,442",NaN,"49,238",NaN,...,"449,430","949,692","27,752","116,961,928","27,388",565,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,994.0,ZFP GEA,0,NaN,0,NaN,0,NaN,0,NaN,...,0,0,0,0,0,0,0,0,0,0
390,996.0,ZFPE Compañía Operadora Clinica Hispanoamericana,0,NaN,0,NaN,0,NaN,0,NaN,...,0,0,0,0,0,0,0,0,0,0
391,997.0,ZFP SurColombiana,0,NaN,0,NaN,0,NaN,0,NaN,...,0,0,0,0,0,0,0,0,0,0
392,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,NaN,0,NaN,0,NaN,0,NaN,...,"158,205","5,042","6,990","28,497,123","2,454",271,0,0,0,0
393,999.0,Países no precisados en otra parte y desconocidos,"1,152,176",NaN,"855,267",NaN,"2,097,960",NaN,"2,987,626",NaN,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df_importations.isna()

,Código,País,Enero - Diciembre 1980,Unnamed: 3,Enero - Diciembre 1981,Unnamed: 5,Enero - Diciembre 1982,Unnamed: 7,Enero - Diciembre 1983,Unnamed: 9,...,Unnamed: 153,Unnamed: 154,Enero - diciembre 2023,Unnamed: 156,Unnamed: 157,Unnamed: 158,Enero - mayo 2024,Unnamed: 160,Unnamed: 161,Unnamed: 162
0,True,True,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
390,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
391,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
392,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
393,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False

In [19]:
Columnas = df_importations.isna().sum()
Columnas

Código                      4
País                        3
Enero - Diciembre 1980      2
Unnamed: 3                394
Enero - Diciembre 1981      2
                         ...
Unnamed: 158                2
Enero - mayo 2024           2
Unnamed: 160                2
Unnamed: 161                2
Unnamed: 162                2
Length: 163, dtype: int64

In [20]:
for i in Columnas.index:
    if Columnas[i] == 394:
        print(i)

Unnamed: 3
Unnamed: 5
Unnamed: 7
Unnamed: 9
Unnamed: 11
Unnamed: 13
Unnamed: 15
Unnamed: 17
Unnamed: 19
Unnamed: 21
Unnamed: 23
Unnamed: 25
Unnamed: 27
Unnamed: 29
Unnamed: 31
Unnamed: 33
Unnamed: 35
Unnamed: 37
Unnamed: 39
Unnamed: 41
Unnamed: 46
Unnamed: 51
Unnamed: 56
Unnamed: 61
Unnamed: 66
Unnamed: 71
Unnamed: 76
Unnamed: 81
Unnamed: 86
Unnamed: 91
Unnamed: 96
Unnamed: 101
Unnamed: 106
Unnamed: 121
Unnamed: 126
Unnamed: 131
Unnamed: 136
Unnamed: 141
Unnamed: 146

In [21]:
for i in Columnas.index:
    if Columnas[i] == 394:
        df_importations.drop(i, axis=1, inplace=True)

df_importations

,Código,País,Enero - Diciembre 1980,Enero - Diciembre 1981,Enero - Diciembre 1982,Enero - Diciembre 1983,Enero - Diciembre 1984,Enero - Diciembre 1985,Enero - Diciembre 1986,Enero - Diciembre 1987,...,Unnamed: 153,Unnamed: 154,Enero - diciembre 2023,Unnamed: 156,Unnamed: 157,Unnamed: 158,Enero - mayo 2024,Unnamed: 160,Unnamed: 161,Unnamed: 162
0,NaN,NaN,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,...,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Total,"4,662,604,264","5,199,155,629","5,477,701,184","4,968,079,999","4,492,392,177","4,130,686,231","3,852,084,997","4,227,977,523",...,"71,446,374,137","40,161,000,492","62,796,636,363","273,157,297,690,829","59,445,304,522","38,053,556,648","25,911,804,734","100,871,611,816,413","24,572,515,154","17,292,003,534"
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13.0,Afganistán,"135,485",0,"74,442","49,238",0,"13,520",0,0,...,"449,430","949,692","27,752","116,961,928","27,388",565,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,994.0,ZFP GEA,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
390,996.0,ZFPE Compañía Operadora Clinica Hispanoamericana,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
391,997.0,ZFP SurColombiana,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,0,0,0,0,0,0,0,...,"158,205","5,042","6,990","28,497,123","2,454",271,0,0,0,0
393,999.0,Países no precisados en otra parte y desconocidos,"1,152,176","855,267","2,097,960","2,987,626","10,040,983","20,897,554","32,834,823","63,302,690",...,0,0,0,0,0,0,0,0,0,0

In [22]:
Filas = df_importations.isna().sum(axis=1)
Filas

0        4
1      124
2        3
3      124
4        2
      ...
389      2
390      2
391      2
392      2
393      2
Length: 394, dtype: int64

In [23]:
for i in Filas.index:
    if Filas[i] == 124:
        print(i)

1
3

In [24]:
for i in Filas.index:
    if Filas[i] == 124:
        df_importations.drop(i, axis=0, inplace=True)

df_importations

,Código,País,Enero - Diciembre 1980,Enero - Diciembre 1981,Enero - Diciembre 1982,Enero - Diciembre 1983,Enero - Diciembre 1984,Enero - Diciembre 1985,Enero - Diciembre 1986,Enero - Diciembre 1987,...,Unnamed: 153,Unnamed: 154,Enero - diciembre 2023,Unnamed: 156,Unnamed: 157,Unnamed: 158,Enero - mayo 2024,Unnamed: 160,Unnamed: 161,Unnamed: 162
0,NaN,NaN,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,...,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos
2,NaN,Total,"4,662,604,264","5,199,155,629","5,477,701,184","4,968,079,999","4,492,392,177","4,130,686,231","3,852,084,997","4,227,977,523",...,"71,446,374,137","40,161,000,492","62,796,636,363","273,157,297,690,829","59,445,304,522","38,053,556,648","25,911,804,734","100,871,611,816,413","24,572,515,154","17,292,003,534"
4,13.0,Afganistán,"135,485",0,"74,442","49,238",0,"13,520",0,0,...,"449,430","949,692","27,752","116,961,928","27,388",565,0,0,0,0
5,15.0,"Aland, Islas",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,17.0,Albania,"1,724",0,0,0,0,0,0,0,...,"320,594","35,547","201,867","856,593,375","188,928","13,099","131,555","513,751,791","125,066","6,365"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,994.0,ZFP GEA,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
390,996.0,ZFPE Compañía Operadora Clinica Hispanoamericana,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
391,997.0,ZFP SurColombiana,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,0,0,0,0,0,0,0,...,"158,205","5,042","6,990","28,497,123","2,454",271,0,0,0,0
393,999.0,Países no precisados en otra parte y desconocidos,"1,152,176","855,267","2,097,960","2,987,626","10,040,983","20,897,554","32,834,823","63,302,690",...,0,0,0,0,0,0,0,0,0,0

## DF Exportaciones

In [25]:
df_exportations

,Código,País,1970,Unnamed: 3,Unnamed: 4,Unnamed: 5,1971,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,2022,Unnamed: 211,Unnamed: 212,Unnamed: 213,2023,Unnamed: 215,Unnamed: 216,2024*,Unnamed: 218,Unnamed: 219
0,NaN,NaN,Kilos Netos,Dólares FOB,Pesos FOB,NaN,Kilos Netos,Dólares FOB,Pesos FOB,NaN,...,Kilos Netos,Dólares FOB,Pesos FOB,NaN,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB
1,NaN,Total,"7,156,313,083","735,657,066",-,NaN,"6,293,567,780","690,008,689",-,NaN,...,"102,131,628,696","56,910,136,648","241,607,564,595,030",NaN,"103,191,548,967","49,769,126,318","215,159,245,675,576","45,438,335,252","20,154,157,442","78,522,240,780,348"
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,ZFP Dorado,0,0,0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-
4,13.0,Afganistán,"7,913","4,185",0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,994.0,ZFP GEA,0,0,0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-
388,996.0,ZFPE Compañía Operadora Clinica Hispanoameri...,0,0,0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-
389,997.0,ZFP SurColombiana,0,0,0,NaN,0,0,0,NaN,...,-,-,-,NaN,"203,700","135,910","540,476,495","144,410","107,475","419,344,080"
390,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,0,0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-
391,999.0,Países no precisados en otra parte y desconoc...,"4,399,265","47,123",0,NaN,0,0,0,NaN,...,-,-,-,NaN,-,-,-,-,-,-

In [26]:
df_exportations.isna()

,Código,País,1970,Unnamed: 3,Unnamed: 4,Unnamed: 5,1971,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,2022,Unnamed: 211,Unnamed: 212,Unnamed: 213,2023,Unnamed: 215,Unnamed: 216,2024*,Unnamed: 218,Unnamed: 219
0,True,True,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
1,True,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,False,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
388,False,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
389,False,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
390,False,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
391,False,False,False,False,False,True,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False

In [27]:
Columnas = df_exportations.isna().sum()
Columnas

Código          3
País            2
1970            1
Unnamed: 3      1
Unnamed: 4      1
               ..
Unnamed: 215    1
Unnamed: 216    1
2024*           1
Unnamed: 218    1
Unnamed: 219    1
Length: 220, dtype: int64

In [28]:
for i in Columnas.index:
    if Columnas[i] == 392:
        print(i)

Unnamed: 5
Unnamed: 9
Unnamed: 13
Unnamed: 17
Unnamed: 21
Unnamed: 25
Unnamed: 29
Unnamed: 33
Unnamed: 37
Unnamed: 41
Unnamed: 45
Unnamed: 49
Unnamed: 53
Unnamed: 57
Unnamed: 61
Unnamed: 65
Unnamed: 69
Unnamed: 73
Unnamed: 77
Unnamed: 81
Unnamed: 85
Unnamed: 89
Unnamed: 93
Unnamed: 97
Unnamed: 101
Unnamed: 105
Unnamed: 109
Unnamed: 113
Unnamed: 117
Unnamed: 121
Unnamed: 125
Unnamed: 129
Unnamed: 133
Unnamed: 137
Unnamed: 141
Unnamed: 145
Unnamed: 149
Unnamed: 153
Unnamed: 157
Unnamed: 161
Unnamed: 165
Unnamed: 169
Unnamed: 173
Unnamed: 177
Unnamed: 181
Unnamed: 185
Unnamed: 189
Unnamed: 193
Unnamed: 197
Unnamed: 201
Unnamed: 209
Unnamed: 213

In [29]:
for i in Columnas.index:
    if Columnas[i] == 392:
        df_exportations.drop(i, axis=1, inplace=True)

df_exportations

,Código,País,1970,Unnamed: 3,Unnamed: 4,1971,Unnamed: 7,Unnamed: 8,1972,Unnamed: 11,...,Unnamed: 208,2022,Unnamed: 211,Unnamed: 212,2023,Unnamed: 215,Unnamed: 216,2024*,Unnamed: 218,Unnamed: 219
0,NaN,NaN,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,...,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB
1,NaN,Total,"7,156,313,083","735,657,066",-,"6,293,567,780","690,008,689",-,"5,718,402,370","865,957,616",...,"155,736,811,057,303","102,131,628,696","56,910,136,648","241,607,564,595,030","103,191,548,967","49,769,126,318","215,159,245,675,576","45,438,335,252","20,154,157,442","78,522,240,780,348"
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,ZFP Dorado,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
4,13.0,Afganistán,"7,913","4,185",0,0,0,0,0,0,...,"16,550,533",-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,994.0,ZFP GEA,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
388,996.0,ZFPE Compañía Operadora Clinica Hispanoameri...,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
389,997.0,ZFP SurColombiana,0,0,0,0,0,0,0,0,...,0,-,-,-,"203,700","135,910","540,476,495","144,410","107,475","419,344,080"
390,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
391,999.0,Países no precisados en otra parte y desconoc...,"4,399,265","47,123",0,0,0,0,"3,568","7,603",...,0,-,-,-,-,-,-,-,-,-

In [30]:
Filas = df_exportations.isna().sum(axis=1)
Filas

0        3
1        2
2      168
3        1
4        1
      ...
387      1
388      1
389      1
390      1
391      1
Length: 392, dtype: int64

In [31]:
for i in Filas.index:
    if Filas[i] == 168:
        print(i)

2

In [32]:
for i in Filas.index:
    if Filas[i] == 168:
        df_exportations.drop(i, axis=0, inplace=True)

df_exportations

,Código,País,1970,Unnamed: 3,Unnamed: 4,1971,Unnamed: 7,Unnamed: 8,1972,Unnamed: 11,...,Unnamed: 208,2022,Unnamed: 211,Unnamed: 212,2023,Unnamed: 215,Unnamed: 216,2024*,Unnamed: 218,Unnamed: 219
0,NaN,NaN,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,...,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB
1,NaN,Total,"7,156,313,083","735,657,066",-,"6,293,567,780","690,008,689",-,"5,718,402,370","865,957,616",...,"155,736,811,057,303","102,131,628,696","56,910,136,648","241,607,564,595,030","103,191,548,967","49,769,126,318","215,159,245,675,576","45,438,335,252","20,154,157,442","78,522,240,780,348"
3,2.0,ZFP Dorado,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
4,13.0,Afganistán,"7,913","4,185",0,0,0,0,0,0,...,"16,550,533",-,-,-,-,-,-,-,-,-
5,15.0,"Aland, Islas",0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,994.0,ZFP GEA,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
388,996.0,ZFPE Compañía Operadora Clinica Hispanoameri...,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
389,997.0,ZFP SurColombiana,0,0,0,0,0,0,0,0,...,0,-,-,-,"203,700","135,910","540,476,495","144,410","107,475","419,344,080"
390,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,0,0,0,0,0,0,0,...,0,-,-,-,-,-,-,-,-,-
391,999.0,Países no precisados en otra parte y desconoc...,"4,399,265","47,123",0,0,0,0,"3,568","7,603",...,0,-,-,-,-,-,-,-,-,-

# Modificar el DF names y localizaciones

In [33]:

#df_importaciones.columns.tolist()
datos = df_importations.iloc[1:, 2:].copy()

# Paso 2: aseguramos que todos sean texto
datos = datos.astype(str)

# Paso 3: limpiamos comas y convertimos a número
datos = datos.applymap(lambda x: pd.to_numeric(str(x).replace(',', '').strip(), errors='coerce'))

# Paso 4: pegamos los datos limpios de vuelta
df_importations.iloc[1:, 2:] = datos
df_importations

/tmp/ipython-input-33-2831959860.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  datos = datos.applymap(lambda x: pd.to_numeric(str(x).replace(',', '').strip(), errors='coerce'))

,Código,País,Enero - Diciembre 1980,Enero - Diciembre 1981,Enero - Diciembre 1982,Enero - Diciembre 1983,Enero - Diciembre 1984,Enero - Diciembre 1985,Enero - Diciembre 1986,Enero - Diciembre 1987,...,Unnamed: 153,Unnamed: 154,Enero - diciembre 2023,Unnamed: 156,Unnamed: 157,Unnamed: 158,Enero - mayo 2024,Unnamed: 160,Unnamed: 161,Unnamed: 162
0,NaN,NaN,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,Dólares CIF,...,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos,Dólares CIF,Pesos CIF,Dólares FOB,Kilos Netos
2,NaN,Total,4662604264,5199155629,5477701184,4968079999,4492392177,4130686231,3852084997,4227977523,...,71446374137,40161000492,62796636363,273157297690829,59445304522,38053556648,25911804734,100871611816413,24572515154,17292003534
4,13.0,Afganistán,135485,0,74442,49238,0,13520,0,0,...,449430,949692,27752,116961928,27388,565,0,0,0,0
5,15.0,"Aland, Islas",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,17.0,Albania,1724,0,0,0,0,0,0,0,...,320594,35547,201867,856593375,188928,13099,131555,513751791,125066,6365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,994.0,ZFP GEA,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
390,996.0,ZFPE Compañía Operadora Clinica Hispanoamericana,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
391,997.0,ZFP SurColombiana,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,0,0,0,0,0,0,0,...,158205,5042,6990,28497123,2454,271,0,0,0,0
393,999.0,Países no precisados en otra parte y desconocidos,1152176,855267,2097960,2987626,10040983,20897554,32834823,63302690,...,0,0,0,0,0,0,0,0,0,0

In [34]:
df_importations['Enero - Diciembre 1980'].info()

<class 'pandas.core.series.Series'>
Index: 392 entries, 0 to 393
Series name: Enero - Diciembre 1980
Non-Null Count  Dtype
--------------  -----
392 non-null    object
dtypes: object(1)
memory usage: 6.1+ KB

In [35]:
datos = df_exportations.iloc[1:, 2:].copy()
datos = datos.astype(str)
datos = datos.applymap(lambda x: pd.to_numeric(str(x).replace(',', '').strip(), errors='coerce'))
df_exportations.iloc[1:, 2:] = datos
df_exportations

/tmp/ipython-input-35-3309020500.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  datos = datos.applymap(lambda x: pd.to_numeric(str(x).replace(',', '').strip(), errors='coerce'))

,Código,País,1970,Unnamed: 3,Unnamed: 4,1971,Unnamed: 7,Unnamed: 8,1972,Unnamed: 11,...,Unnamed: 208,2022,Unnamed: 211,Unnamed: 212,2023,Unnamed: 215,Unnamed: 216,2024*,Unnamed: 218,Unnamed: 219
0,NaN,NaN,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,...,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB,Kilos Netos,Dólares FOB,Pesos FOB
1,NaN,Total,7156313083,735657066,NaN,6293567780,690008689,NaN,5718402370,865957616,...,155736811057303,102131628696.0,56910136648.0,241607564595030.0,103191548967.0,49769126318.0,215159245675576.0,45438335252.0,20154157442.0,78522240780348.0
3,2.0,ZFP Dorado,0,0,0.0,0,0,0.0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13.0,Afganistán,7913,4185,0.0,0,0,0.0,0,0,...,16550533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,15.0,"Aland, Islas",0,0,0.0,0,0,0.0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,994.0,ZFP GEA,0,0,0.0,0,0,0.0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,996.0,ZFPE Compañía Operadora Clinica Hispanoameri...,0,0,0.0,0,0,0.0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
389,997.0,ZFP SurColombiana,0,0,0.0,0,0,0.0,0,0,...,0,NaN,NaN,NaN,203700.0,135910.0,540476495.0,144410.0,107475.0,419344080.0
390,998.0,ZFPE Sociedad Portuaria Regional de Cartagena,0,0,0.0,0,0,0.0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,999.0,Países no precisados en otra parte y desconoc...,4399265,47123,0.0,0,0,0.0,3568,7603,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Crear un filtro para eliminar los paises que no tengan ubicacion

> Hacer un merge entre el dataframe *df_names* y *df_locations*

In [36]:
df_merged = pd.merge(df_names, df_locations, left_on='en', right_on='name')
df_merged

,id,alpha2,alpha3,ar,bg,cs,da,de,el,en,...,sr,sv,th,uk,zh,zh-tw,country,latitude,longitude,name
0,4,af,afg,أفغانستان,Афганистан,Afghánistán,Afghanistan,Afghanistan,Αφγανιστάν,Afghanistan,...,Avganistan,Afghanistan,อัฟกานิสถาน,Афганістан,阿富汗,阿富汗,AF,3.393.911,67.709.953,Afghanistan
1,8,al,alb,ألبانيا,Албания,Albánie,Albanien,Albanien,Αλβανία,Albania,...,Albanija,Albanien,แอลเบเนีย,Албанія,阿尔巴尼亚,阿爾巴尼亞,AL,41.153.332,20.168.331,Albania
2,12,dz,dza,الجزائر,Алжир,Alžírsko,Algeriet,Algerien,Αλγερία,Algeria,...,Alžir,Algeriet,แอลจีเรีย,Алжир,阿尔及利亚,阿爾及利亞,DZ,28.033.886,1.659.626,Algeria
3,16,as,asm,ساموا الأمريكية,Американска Самоа,Americká Samoa,Amerikansk Samoa,Amerikanisch-Samoa,Αμερικανική Σαμόα,American Samoa,...,Američka Samoa,Amerikanska Samoa,อเมริกันซามัว,Американське Самоа,美属萨摩亚,美屬薩摩亞,AS,-14.270.972,-170.132.217,American Samoa
4,20,ad,and,أندورا,Андора,Andorra,Andorra,Andorra,Ανδόρρα,Andorra,...,Andora,Andorra,อันดอร์รา,Андорра,安道尔,安道爾,AD,42.546.245,1.601.554,Andorra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,876,wf,wlf,واليس وفوتونا,Уолис и Футуна,Wallis a Futuna,Wallis og Futuna,Wallis und Futuna,Ουαλίς και Φουτουνά,Wallis and Futuna,...,Valis i Futuna,Wallis- och Futunaöarna,วอลิสและฟูตูนา,Волліс і Футуна,瓦利斯和富图纳,瓦利斯和富圖那,WF,-13.768.752,-177.156.097,Wallis and Futuna
203,732,eh,esh,الصحراء الغربية,Западна Сахара,Západní Sahara,Vestsahara,Westsahara,Δυτική Σαχάρα,Western Sahara,...,Zapadna Sahara,Västsahara,เวสเทิร์นสะฮารา,Західна Сахара,西撒哈拉,西撒哈拉,EH,24.215.527,-12.885.834,Western Sahara
204,887,ye,yem,اليمن,Йемен,Jemen,Yemen,Jemen,Υεμένη,Yemen,...,Jemen,Jemen,เยเมน,Ємен,也门,葉門,YE,15.552.727,48.516.388,Yemen
205,894,zm,zmb,زامبيا,Замбия,Zambie,Zambia,Sambia,Ζάμπια,Zambia,...,Zambija,Zambia,แซมเบีย,Замбія,赞比亚,尚比亞,ZM,-13.133.897,27.849.332,Zambia
206,716,zw,zwe,زيمبابوي,Зимбабве,Zimbabwe,Zimbabwe,Simbabwe,Ζιμπάμπουε,Zimbabwe,...,Zimbabve,Zimbabwe,ซิมบับเว,Зімбабве,津巴布韦,辛巴威,ZW,-19.015.438,29.154.857,Zimbabwe

In [40]:
df_merged.drop(df_merged.columns[:9], axis=1, inplace=True)

In [42]:
df_merged.drop(df_merged.columns[1], axis=1, inplace=True)

In [44]:
df_merged.drop(df_merged.columns[2:-3], axis=1, inplace=True)

In [46]:
df_merged.drop(df_merged.columns[-1], axis=1, inplace=True)

In [47]:
df_merged

,en,es,latitude,longitude
0,Afghanistan,Afganistán,3.393.911,67.709.953
1,Albania,Albania,41.153.332,20.168.331
2,Algeria,Argelia,28.033.886,1.659.626
3,American Samoa,Samoa Americana,-14.270.972,-170.132.217
4,Andorra,Andorra,42.546.245,1.601.554
...,...,...,...,...
202,Wallis and Futuna,Wallis y Futuna,-13.768.752,-177.156.097
203,Western Sahara,República Árabe Saharaui Democrática,24.215.527,-12.885.834
204,Yemen,Yemen,15.552.727,48.516.388
205,Zambia,Zambia,-13.133.897,27.849.332
206,Zimbabwe,Zimbabue,-19.015.438,29.154.857