<a href="https://colab.research.google.com/github/Davichobacter/ds-4geeks/blob/main/TableOne_intro(Ai_page).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/job_sector_wage.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
!pip install tableone > null

In [ ]:
from tableone import TableOne

In [ ]:
df.describe()

             wage         age  consumption
count  210.000000  210.000000   210.000000
mean    86.574791   31.597841    27.449586
std     28.834764    1.977201    36.102628
min     45.023217   24.998936     0.001692
25%     51.262237   30.301961     6.292992
50%     89.988178   31.596118    13.808425
75%    118.487498   32.843222    32.466710
max    125.523800   37.594351   204.897051

In [ ]:
df['sector'].value_counts()

sector
Financial     63
Technology    60
IT            45
Retail        42
Name: count, dtype: int64

In [ ]:
df['job'].value_counts()

job
economistas       70
data_scientist    70
BI                70
Name: count, dtype: int64

In [ ]:
df.groupby(by=['job'])[['consumption', 'wage', 'age']].agg(['mean', 'std'])

               consumption                   wage                  age  \
                      mean        std        mean       std       mean
job
BI               51.565541  50.152249   90.091558  2.075776  31.820041
data_scientist   20.566855  20.570126  119.823517  2.182521  31.785841
economistas      10.216362   8.381299   49.809298  2.005249  31.187642


                     std
job
BI              1.732708
data_scientist  2.041727
economistas     2.100883

In [ ]:
df.groupby(by=['sector'])[['consumption', 'wage', 'age']].agg(['mean', 'std'])

           consumption                  wage                   age
                  mean        std       mean        std       mean       std
sector
Financial    25.617604  34.870592  86.346360  31.865794  31.562043  2.073970
IT           21.271780  29.437207  89.819744  29.980393  31.629331  2.129765
Retail       37.047144  41.262274  88.642145  23.724950  31.693214  1.884720
Technology   27.288230  37.572124  82.933781  28.145213  31.545051  1.861618

In [ ]:
TableOne(df,
         nonnormal = ['consumption'],
         categorical=['sector'],
         groupby='job',
         pval=True,
         htest_name=True)

                                       Grouped by job
                                              Missing          Overall                BI   data_scientist     economistas P-Value            Test
n                                                                  210                70               70              70
wage, mean (SD)                                     0      86.6 (28.8)        90.1 (2.1)      119.8 (2.2)      49.8 (2.0)  <0.001   One-way ANOVA
age, mean (SD)                                      0       31.6 (2.0)        31.8 (1.7)       31.8 (2.0)      31.2 (2.1)   0.104   One-way ANOVA
consumption, median [Q1,Q3]                         0  13.8 [6.3,32.5]  30.4 [11.5,75.1]  14.7 [5.2,28.0]  7.8 [4.3,14.7]  <0.001  Kruskal-Wallis
sector, n (%)               Financial                        63 (30.0)         12 (17.1)        26 (37.1)       25 (35.7)   0.011     Chi-squared
                            IT                               45 (21.4)         13 (18.6)        18 (25.7)       14 (20.0)
                            Retail                           42 (20.0)         23 (32.9)        10 (14.3)        9 (12.9)
                            Technology                       60 (28.6)         22 (31.4)        16 (22.9)       22 (31.4)

# Research about kruskall wallis and wilcoxon sum rank test.